"""LLM-callable tool for retrieving real code examples from indexed documentation."""

from __future__ import annotations

from typing import Any

from ..doc_reader.indexer import DocIndex
from ..doc_reader.query import DocQuery
from ..doc_reader.scanner import scan_directory, scan_installed_package
from .base import BaseTool, ToolResult


class DocExamplesTool(BaseTool):
    """Tool for searching code examples from real package documentation.

    The LLM calls this tool before writing code that uses a library to get
    accurate, up-to-date examples directly from installed package source.
    """

    name = "doc_examples"
    description = (
        "Search code examples extracted from real package documentation. "
        "Use this BEFORE writing code that uses a library to get accurate, "
        "up-to-date examples directly from the source. "
        "Returns real examples from docstrings — not generated by AI."
    )

    def __init__(self, index: DocIndex) -> None:
        """Initialize the tool with a shared DocIndex.

        Args:
            index: The documentation index to use for searches.
        """
        self._index = index
        self._query = DocQuery(index)

    def get_schema(self) -> dict[str, Any]:
        """Return OpenAI function calling schema for this tool.

        Returns:
            Dict with type and function keys in OpenAI format.
        """
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": {
                    "type": "object",
                    "properties": {
                        "query": {
                            "type": "string",
                            "description": (
                                "What you're looking for, e.g. "
                                "'pandas groupby aggregation' or 'requests post json'"
                            ),
                        },
                        "package": {
                            "type": "string",
                            "description": (
                                "Optional: index this package first if not already indexed, "
                                "e.g. 'requests', 'pathlib'"
                            ),
                        },
                        "top_k": {
                            "type": "integer",
                            "description": (
                                "Max number of functions to return examples for (default 3)"
                            ),
                            "default": 3,
                        },
                    },
                    "required": ["query"],
                },
            },
        }

    def execute(  # type: ignore[override]
        self,
        query: str,
        package: str | None = None,
        top_k: int = 3,
    ) -> ToolResult:
        """Execute the doc examples search.

        If a package is specified and not yet indexed, scans and indexes it first.

        Args:
            query: Search query string.
            package: Optional package name to index if not already indexed.
            top_k: Maximum number of functions to return examples for.

        Returns:
            ToolResult with formatted examples or a descriptive message.
        """
        # If package specified and not yet indexed, index it now
        if package:
            pkg_top = package.split(".")[0]
            indexed = self._index.stats().get("indexed_packages", [])
            if pkg_top not in indexed:
                try:
                    entries = scan_installed_package(pkg_top)
                    self._index.add_many(entries)
                except Exception:
                    # Don't fail — just proceed with whatever is in the index
                    pass

        if self._index.is_empty:
            return ToolResult(
                content=(
                    "No documentation indexed yet. "
                    "Use /index <package> to index a package first, "
                    "or specify the 'package' parameter."
                ),
                is_error=False,
            )

        result = self._query.find_examples(query, top_k=top_k)
        if not result:
            stats = self._index.stats()
            return ToolResult(
                content=(
                    f"No examples found for {query!r}. "
                    f"Index has {stats['total_entries']} entries from: "
                    f"{stats['indexed_packages']}"
                ),
                is_error=False,
            )

        return ToolResult(content=result)
